### ISSUE TITLE
Add vendor tarball for releases

### ISSUE THREAD

**Issue by travier** [1player/host-spawn#14]
For Flatpak builds, we do not have network access so it's much easier for us if we have a vendor tarball that we can pull in.

The idea is to run the following and add it to each release:
```
$ git clean -fdx
$ go mod vendor
$ tar --create --zst --file host-spawn-vendor.tar.zst
```

**Comment by 1player** [comment]
The latest release 1.3.0 includes this tarball, please have a look and let me know if it works for you.

**Comment by travier** [comment]
Thanks, will take a look
