### ISSUE TITLE
Forward signals via HostCommandSignal

### ISSUE THREAD

**Issue by mitchellh** [1player/host-spawn#18]
Signals received from the `host-spawn` side should get sent to the host command using `HostCommandSignal`: https://docs.flatpak.org/en/latest/libflatpak-api-reference.html#gdbus-method-org-freedesktop-Flatpak-Development.HostCommandSignal

Right now if I spawn a process on the host and send signals, the host side never receives them. I believe this is the issue but not 100% sure.

**Comment by 1player** [comment]
Seems like a legit request, but I don't have time to work on it. PR is welcome.

**Comment by 1player** [comment]
I have a WIP version in the `handle-signals` branch that forwards signals. I still need a little time to test it before merging
