### ISSUE TITLE
The name org.freedesktop.Flatpak was not provided by any .service files

### ISSUE THREAD

**Issue by neurosnap** [1player/host-spawn#20]
Hi!  I'm using `distrobox` and want to run `podman` inside my containers.  [I followed your guide](https://github.com/1player/host-spawn#creating-shims-for-host-binaries) but I still end up with:

```
The name org.freedesktop.Flatpak was not provided by any .service files
```

Any idea what I'm missing?  If it helps, I'm on openSUSE MicroOS.  Any guidance would be greatly appreciated!

**Comment by 1player** [comment]
I've never used MicroOS. Is flatpak installed and running on the host? `host-spawn` to work uses some development API exposed by the Flatpak DBus service, which needs to be running on the host.

**Comment by 1player** [comment]
As I mentioned, seems like a host issue. If this is still a problem, please post on the Discussion board.
