### ISSUE TITLE
figure out which env variables to pass to the spawned process

### ISSUE THREAD

**Issue by 1player** [1player/host-spawn#3]
Right now we hardcode `$TERM`, which should probably be inherited along with other variables. See how Tilix does it.

**Comment by 1player** [comment]
`$TERM` now is inherited, but this question is still open. Tilix (https://github.com/gnunn1/tilix/blob/master/source/gx/tilix/terminal/terminal.d) apparently passes through most of the env variables except a handful, but I'm not sure this is the correct idea.

**Comment by 89luca89** [comment]
From my testing, especially if we talk about spawning shells, it's not that important to pass the whole env
For other stuff it might be useful

**Comment by tinywrkb** [comment]
> apparently passes through most of the env variables except a handful, but I'm not sure this is the correct idea.

Please don't, or at least makes this optional. I'm already setting the systemd user session environment (actually only needed is `flatpak-session-helper.service`), and would appreciate not having Flatpak-specific environment variables pollute the host spawned process environment.  
I have a bunch of these Flatpak-specific environment variables and would like them to stay in the sandbox.

One approach of handling common environment variables to host shell and Flatpak-spawned processes is to set them first in the systemd user environment (`systemd.generator` and/or `environment.d`), and then import them into the host shell environment.  
For example, this is how I import them into the host shell:

```
# /etc/bash.functions

if [ -z "$OS_BASH_FUNCTIONS" ]; then
  export OS_BASH_FUNCTIONS=1

  source_executable_output(){
  set -a
  source /dev/fd/0 <<EOF
$($1)
EOF
  set +a
  }
  export -f source_executable_output

  import_systemd_environment(){
    local env_gens=()
    local env_gen_dirs=()

    # directories order according to systemd.generator.7 man page
    for d in /{run,etc,usr/lib}/systemd/user-environment-generators; do
      [ -d $d ] && env_gen_dirs+=($d)
    done

    # find all environment generators, only keep file name
    for f in $(find ${env_gen_dirs[@]} -perm -0005 -type f); do
      env_gens+=($(basename $f))
    done

    # sort and remove duplicates
    IFS=$'\n' env_gens=($(sort -u <<<${env_gens[*]}))
    unset IFS

    for env_gen in ${env_gens[@]}; do
      for d in ${env_gen_dirs[@]}; do
        if [ -f ${d}/${env_gen} ]; then
          source_executable_output ${d}/${env_gen}
          break
        fi
      done
    done
  }
  export -f import_systemd_environment
fi
```

```
# bash.bashrc
...

# load bash functions
[ -r /etc/bash.functions ] && . /etc/bash.functions

if [ -z "$IMPORTED_SYSTEMD_ENV" ]; then
  export IMPORTED_SYSTEMD_ENV=1
  import_systemd_environment
fi

```

**Comment by 1player** [comment]
Yeah, I'm more and more convinced only $TERM needs to be set, but everything else is inherited provided you've configured your host correctly, i.e. by setting user env variables in your user systemd instance or inside .zshenv/.bash_profile instead of .zshrc/.bashrc, etc.

I'm closing this, please reopen if anyone knows of anything that *needs* to be set to function correctly.
