### ISSUE TITLE
Create build script for targeting single architecture

### ISSUE THREAD

**Issue by klugier** [1player/host-spawn#31]
Sometimes, there might be need to build host-spawn for single architecture. The good example is to build it within FlatHub pipeline. Currently, I am working on porting [TheIDE](https://www.ultimatepp.org/) to flatpak that is heavenly basing on host-spawn. One of the comments from the maintainers I received is can I build it instead of download pre-build binary package?

So, I assume we need something like ./build-host-platfrom that will generate binary in the host os operating system and architecture.

Reference:
- https://github.com/flathub/flathub/pull/4778/files#r1425341594 - my discussion with FlatHub maitaners and suggestion about building host-spawn from scratch during FlatHub CI/CD.

**Comment by 1player** [comment]
Not much time to look into this, right now. My suggestion for a PR is to have a build.sh script that takes an architecture as argument and creates a binary, and build-all.sh that on a for loop builds for all supported architectures, listed at https://github.com/1player/host-spawn/blob/d1b5a7092d604f8467bc57a5470c3e25969da196/build.sh#L5

build-host-platform.sh isn't needed in this case, one would be able to do `build.sh $(uname -m)`
