### ISSUE TITLE
Tags should have v prefix

### ISSUE THREAD

**Issue by klugier** [1player/host-spawn#32]
It looks like the tagging policy for this repo use non standard way to do in the context of GoLang world. So, instead of having 1.5.0 tag, there should be v1.5.0.

For example all of packages used in this project are using this convention:
- https://github.com/godbus/dbus - v5.1.0
- https://github.com/pkg/term - v1.1.0
- https://golang.org/x/sys - v.0.15.0

**Comment by 1player** [comment]
This is not intended to be used as a library — so is that important?

In any case, I'll try to remember to use v<something>

**Comment by 1player** [comment]
Fixed in latest tag
