### ISSUE TITLE
Ability to set Working Directory of Child Process

### ISSUE THREAD

**Issue by someone13574** [1player/host-spawn#35]
It would be nice if it was possible to set the working directory of the child process like is possible with the `--directory` parameter of flatpak-spawn.

**Comment by 1player** [comment]
What is the use case?

**Comment by someone13574** [comment]
Spawning git in a specific repository on the host system. I’m working on flatpak support for [Zed](https://github.com/zed-industries/zed)

**Comment by 1player** [comment]
Merged the new flag "-cwd". Will be part of the v1.6.0 release
